#!/bin/bash
message="$1"
echo $message
## format to parse to curl
## echo Sending message: $message
msg_content=\"$message\"

## discord webhook
url='YOUR URL HERE'
curl -H "Content-Type: application/json" -X POST -d "{\"content\": $msg_content}" $url
